name: Update theme list

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  update-themes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        working-directory: ./.github/workflows/update-themes
        run: npm ci

      - name: Run TS Action
        working-directory: ./.github/workflows/update-themes
        run: npm run start

      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit latest images
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
<<<<<<< HEAD
          git add ./github/workflows/update-themes/all_themes.json
=======
          git add ./.github/workflows/update-themes/all_themes.json
>>>>>>> 9df7b3b (ðŸ˜œ)
          git commit -m "New Theme"
          git push
